### ISSUE TITLE
Which version of client matching this server version ?

### ISSUE THREAD

**Issue by GF-Huang** [retep998/Vana#3]
Hello, Great Man.
If I want to play, which version of client i need to download? Or any client source code is existing ?

**Comment by retep998** [comment]
https://github.com/retep998/Vana/blob/buis_vana_overhaul/src/Common/MapleVersion.hpp#L54

``` C++
#define MAPLE_VERSION 75
```

Nexon's MapleStory client is proprietary and closed source, and thus nobody has the source code for it. You'll need to get a localhost or a redirector.

**Comment by LazyBui** [comment]
Closing as not a bug.
