### ISSUE TITLE
WorldServer can not connect to LoginServer?

### ISSUE THREAD

**Issue by icelemon1314** [retep998/Vana#30]
When I open WorldServer.exe,the window has no output.

I debug the program to find out:session->send() execution,the loginServer unable to receive the packet(i set a bp at login_server_accepted_session::handle(packet_reader &reader),The program did not break ).

I used wireshark to capture 8484 port packets, not to see packets

I'm not sure where the problem is?

thx.

my external_ip config is 
// wanIp changed for some reason

```
external_ip = {
	makeIp("127.0.0.1", "255.0.0.0"),
	makeIp("10.0.0.106", "255.255.255.0"), 
	makeIp("123.123.123.123","0.0.0.0")
};
```

```
-- What IP and port should the server use to connect to the LoginServer?
login_ip = "127.0.0.1";
login_inter_port = 8484;
```

```
auto abstract_server::send_auth(ref_ptr<session> session) const -> void {
        // the login server can not rec the packet
	session->send( 
		packets::send_password(
			utilities::misc::get_server_type(session->get_type()),
			get_inter_password(),
			m_external_ips));
}
```

**Comment by diamondo25** [comment]
`login_inter_port` is wrong, it should be 8485. See original config: https://github.com/retep998/Vana/blob/buis_vana_overhaul/conf/connection_properties.lua

**Comment by icelemon1314** [comment]
The problem is solved.thx.
